import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';
import { Layout, Page, Text, Link, Button, Code } from '@vercel/examples-ui';
import { STORE_CLOSED, CLICKED_BUTTON } from 'lib/flags';
import { sendEvent } from 'lib/adobe/events';

// These could also be generated by making a request to Adobe Target
const FLAGS = ['expA', 'expB'];
const getEventToken = (flag: string) => Cookies.get(`${flag}-etoken`);

export function getStaticPaths() {
  return {
    paths: FLAGS.map((flag) => ({ params: { exp: flag } })),
    // New experiments could be allowed dinamically with `fallback: 'true' | 'blocking'`
    fallback: false,
  };
}

export function getStaticProps({ params }) {
  return { props: { exp: params.exp } };
}

export default function Exp({ exp }) {
  const router = useRouter();
  const [done, setDone] = useState(false);

  useEffect(() => {
    if (done) return;
    if (!done && router.isReady) {
      // Register a page view
      sendEvent({
        mbox: STORE_CLOSED,
        type: 'display',
        eventToken: getEventToken(exp),
      })
        .then(() => {
          console.log('Page view!');
        })
        .catch(console.error)
        .finally(() => {
          setDone(true);
        });
    }
  }, []);

  const handleClick = async () => {
    await sendEvent({
      mbox: CLICKED_BUTTON,
      type: 'click',
      eventToken: getEventToken(exp),
    });
    console.log('Event sent!');
  };

  return (
    <Page>
      <Text variant="h1" className="mb-6">
        SSG + Middleware Rewrites
      </Text>
      <>
        <Text className="mb-4">
          You&apos;re looking at text selected by the experiment <b>{exp}</b>.
          This is also the default content if Target fails to load.
        </Text>
        <Button
          variant="secondary"
          className="mr-2.5 mb-4"
          onClick={handleClick}
        >
          Send click conversion to Target
        </Button>
      </>
      <Text className="mb-4">
        You're currently on <Code>/ssg</Code> and the path{' '}
        <Code>/static/{exp}</Code> is being rendered.
      </Text>
      <Link href="/">Go back to /</Link>
    </Page>
  );
}

Exp.Layout = Layout;
